name: Deploy to Multiple Clients

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Likhona Lethu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "hthabang23@gmail.com"
        git config --global user.name "dev-kaycee"
        
        # Clone the target repository
        git clone "https://oauth2:${GITHUB_TOKEN}@github.com/dev-kaycee/likhona-lethu.git" client1_repo
        
        # Clear existing files in cloned repo (except .git)
        cd client1_repo
        git rm -rf . || true
        
        # Copy files from source repository
        cp -R ../. ./
        
        # Remove unnecessary directories and files
        rm -rf .git .github vendor
        
        # Stage, commit, and push changes
        git add .
        git commit -m "Automated deployment from main branch" || exit 0
        git push