name: Clone and Push to Another Repo

on:
  push:
    branches:
      - main

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Clone target repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dev-kaycee/likhona-lethu.git
        cd likhona-lethu
        git remote add source https://github.com/${{ github.repository }}.git
        git pull source main

    - name: Push to target repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd likhona-lethu
        git push origin main